apiVersion: cluster.goharbor.io/v1
kind: HarborCluster
metadata:
  name: harborcluster-sample
spec:
  redis:
    kind: "inCluster"
    spec:
      schema: "sentinel"
  adminPasswordSecret: "test"
  database:
    kind: "inCluster"
    spec:
      replicas: 3
  publicURL: "https://harbor.test.com"
  replicas: 1
  storage:
    kind: "inCluster"
    options:
      provider: minIO
  version: "v1.10.2"
