apiVersion: v1
kind: Namespace
metadata:
  name: harbor-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: psql-operator-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-operator-ns